# Generated by Django 4.0.3 on 2022-03-16 19:59

import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organizations/logos/%Y/%m/%d/",
                        validators=[main.validators.validate_image_file],
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(editable=False, max_length=250)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            (
                                "advertising_media_communications",
                                "Advertising, Media & Communications",
                            ),
                            (
                                "agriculture_fishing_forestry",
                                "Agriculture, Fishing & Forestry",
                            ),
                            ("automotive_aviation", "Automotive & Aviation"),
                            (
                                "banking_finance_insurance",
                                "Banking, Finance & Insurance",
                            ),
                            ("construction", "Construction"),
                            ("energy_utilities", "Energy & Utilities"),
                            ("enforcement_security", "Enforcement & Security"),
                            ("government", "Government"),
                            ("healthcare", "Healthcare"),
                            ("hospitality_hotel", "Hospitality & Hotel"),
                            ("it_telecoms", "IT & Telecoms"),
                            ("law_compliance", "Law & Compliance"),
                            (
                                "manufacturing_warehousing",
                                "Manufacturing & Warehousing",
                            ),
                            ("ngo_npo_charity", "NGO, NPO & Charity"),
                            ("recruitment", "Recruitment"),
                            ("retail_fashion_fmcg", "Retail, Fashion & FMCG"),
                            ("shipping_logistics", "Shipping & Logistics"),
                            ("tourism_travel", "Tourism & Travel"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "functions",
                    models.CharField(
                        choices=[
                            (
                                "accounting_auditing_finance",
                                "Accounting, Auditing & Finance",
                            ),
                            ("admin_office", "Admin & Office"),
                            ("building_architecture", "Building & Architecture"),
                            (
                                "community_social_services",
                                "Community & Social Services",
                            ),
                            ("consulting_strategy", "Consulting & Strategy"),
                            ("creative_design", "Creative & Design"),
                            ("customer_service_support", "Customer Service & Support"),
                            (
                                "driver_transport_services",
                                "Driver & Transport Services",
                            ),
                            ("engineering_technology", "Engineering & Technology"),
                            ("farming_agriculture", "Farming & Agriculture"),
                            ("food_services_catering", "Food Services & Catering"),
                            ("health_safety", "Health & Safety"),
                            ("human_resources", "Human Resources"),
                            ("legal_services", "Legal Services"),
                            (
                                "management_business_development",
                                "Management & Business Development",
                            ),
                            ("marketing_communications", "Marketing & Communications"),
                            ("medical_pharmaceutical", "Medical & Pharmaceutical"),
                            (
                                "product_project_management",
                                "Product & Project Management",
                            ),
                            (
                                "quality_control_assurance",
                                "Quality Control & Assurance ",
                            ),
                            (
                                "research_teaching_training",
                                "Research, Teaching & Training",
                            ),
                            ("sales", "Sales"),
                            ("software_data", "Software & Data"),
                            ("supply_chain_procurement", "Supply Chain & Procurement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract/Consultancy"),
                            ("internship", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Entry Level"),
                            (2, "Intermediate"),
                            (3, "Mid-Level"),
                            (4, "Senior or executive-level"),
                        ]
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                ("min_salary", models.IntegerField(blank=True, default=0)),
                ("max_salary", models.IntegerField(blank=True, default=0)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False, editable=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                ("slug", models.SlugField(editable=False, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_jobs",
                        to="main.organization",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={"ordering": ["deadline", "title"],},
        ),
    ]
