# Generated by Django 4.0.3 on 2022-03-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_job_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="functions",
            field=models.CharField(
                choices=[
                    ("quality_assurance", "Quality Assurance"),
                    ("product", "Product Management"),
                    ("devops", "DevOps"),
                    ("design", "Product & UI/UX Design"),
                    ("software_engineering", "Software Engineering"),
                    ("architect", "Archictect"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="timezone",
            field=models.IntegerField(
                choices=[
                    (-3, "UTC-3"),
                    (-2, "UTC-2"),
                    (-1, "UTC-1"),
                    (0, "UTC"),
                    (1, "UTC+1"),
                    (2, "UTC+2"),
                    (3, "UTC+3"),
                ],
                max_length=30,
            ),
        ),
    ]
