# Generated by Django 4.0.3 on 2022-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="resumes/%Y/%m/%d/"
            ),
        ),
    ]
