# Generated by Django 4.0.3 on 2022-03-16 21:37

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_application_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/%Y/%m/%d/",
                validators=[main.validators.validate_resume_file],
            ),
        ),
    ]
