# Generated by Django 4.0.3 on 2022-03-16 21:54

import django_countries.fields
from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_application_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=254)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/%Y/%m/%d/",
                        validators=[main.validators.validate_resume_file],
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("created_date",),
            },
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "New"),
                    (2, "Rejected"),
                    (3, "Set up interview"),
                    (4, "Approved"),
                    (5, "On Hold"),
                    (6, "Cancelled"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="timezone",
            field=models.IntegerField(
                choices=[
                    (-3, "UTC-3"),
                    (-2, "UTC-2"),
                    (-1, "UTC-1"),
                    (0, "UTC"),
                    (1, "UTC+1"),
                    (2, "UTC+2"),
                    (3, "UTC+3"),
                ]
            ),
        ),
    ]
