# Generated by Django 4.0.3 on 2022-03-16 23:40

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_resume_application_status_alter_job_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True, null=True)),
                ("phone_number", models.CharField(max_length=30)),
                (
                    "job_description_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/%Y/%m/%d/",
                        validators=[main.validators.validate_resume_file],
                    ),
                ),
                ("job_description_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
