# Generated by Django 4.0.3 on 2022-03-17 00:06

from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_opening"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="team/photos/%Y/%m/%d/",
                        validators=[main.validators.validate_image_file],
                    ),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimonial", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=100)),
            ],
        ),
    ]
