# Generated by Django 3.2.9 on 2022-05-04 15:17

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models

import main.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_teammember_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("linkedin", models.URLField(blank=True, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("phone_number", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=200)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resumes/%Y/%m/%d/",
                        validators=[main.validators.validate_resume_file],
                    ),
                ),
                (
                    "timezone",
                    models.IntegerField(
                        choices=[
                            (-3, "UTC-3"),
                            (-2, "UTC-2"),
                            (-1, "UTC-1"),
                            (0, "UTC"),
                            (1, "UTC+1"),
                            (2, "UTC+2"),
                            (3, "UTC+3"),
                        ]
                    ),
                ),
                (
                    "availability",
                    models.IntegerField(
                        choices=[
                            (1, "Immediate"),
                            (2, "Less than 2 weeks"),
                            (3, " Less than 4 weeks,"),
                            (4, "More than 4 weeks"),
                        ]
                    ),
                ),
                ("contact_future_opportunities", models.BooleanField(default=True)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="team/photos/%Y/%m/%d/",
                        validators=[main.validators.validate_image_file],
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
