# Generated by Django 4.0.3 on 2022-05-05 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_teammember_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_title', models.CharField(max_length=300, unique=True)),
                ('patent_office', models.CharField(max_length=100, unique=True)),
                ('patient_url', models.URLField()),
                ('patent_number', models.CharField(max_length=100)),
                ('patent_state', models.CharField(choices=[('issued', 'Issued'), ('pending', 'Pending')], max_length=50, unique=True)),
                ('patent_date', models.DateField(unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_patents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
