# Generated by Django 4.0.3 on 2022-05-04 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_teammember_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('will_expire', models.BooleanField(default=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(null=True)),
                ('credential_id', models.CharField(max_length=100, null=True)),
                ('credential_url', models.URLField(null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
