# Generated by Django 4.0.3 on 2022-05-05 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0011_workexperience_start_date_alter_job_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_experiences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workexperience", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="workexperience", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="workexperience", name="start_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
