# Generated by Django 4.0.3 on 2022-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_workexperience_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
