# Generated by Django 4.0.3 on 2022-05-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_certification_description_and_more'),
        ('main', '0013_alter_workexperience_description'),
    ]

    operations = [
    ]
