# Generated by Django 4.0.3 on 2022-05-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_award'),
        ('main', '0013_alter_workexperience_description'),
    ]

    operations = [
    ]
